import Head from 'next/head'
import NavBar from '@/components/NavBar'
import { useEffect, useState } from 'react'
import axios from 'axios';
import { Skeleton } from '@mui/material';


export default function Home() {

  const [tasks, setTasks] = useState({ "documents": [{ "_id": "63fcc4f253a94da086f96d1f", "mensaje": "dwaedawdaw", "nombre_profesor": "", "grupo": "", "materia": "", "clase": { "$timestamp": "0" }, "chat_id": "", "enviado": false }, { "_id": "63fcce9de24a372b797b0d7b", "mensaje": "No hay clase", "nombre_profesor": "Noe", "grupo": "2TM2", "horario": "8:30", "dia": "lunes", "materia": "Aplicaciones" }, { "_id": "63fccefbe24a372b797b0d7c", "mensaje": "Llegar 10 min antes", "nombre_profesor": "Zavala", "grupo": "2TM2", "horario": "10:00", "dia": "lunes", "materia": "Procesamiento de señales" }, { "_id": "63fccf7589227d0020b96614", "mensaje": null, "nombre_profesor": null, "grupo": null, "horario": null, "dia": null, "materia": null }, { "_id": "63fccff46b21209cc96b21a2", "mensaje": "No habra practica", "nombre_profesor": "Cyntia", "grupo": "2TM4", "horario": "7:00", "dia": "miercoles", "materia": "Protocolos" }, { "_id": "63fcd0306b21209cc96b21a3", "mensaje": "No habra practica", "nombre_profesor": "Noe", "grupo": "2TM4", "horario": "7:00", "dia": "miercoles", "materia": "Sistemas distribuidos" }, { "_id": "63ff560e1a8d5bf3610b90bd", "mensaje": "", "nombre_profesor": "", "grupo": "", "horario": "", "dia": "", "materia": "" }] });
  const [prueba, setPrueba] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const response = await axios.get("https://apptelegram.repl.co/");
        console.log(response.data.documents);
      } catch (error) {
        console.log(error);
      }
    })
  },[tasks])

  useEffect(() => {
    setTimeout(() => {
      setPrueba(true);
    },3000)
  },[])

  return (
    <div className=''>
      <Head>
        <title>Incidencias Profesores</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='p-4 flex flex-col items-start mb-24'>
        {prueba ? (
          tasks.documents.map((card) => {
            return (
              <div key={card._id} className="p-4 shadow-lg w-full border">
                <h2 className='font-semibold text-xl'> {card.materia} - {card.grupo}</h2>
                <div className='text-gray-600'>
                  <h4 className='text-lg'>{card.nombre_profesor ? card.nombre_profesor : "Miguel"}</h4>
                  <h5>{card.dia} - {card.horario}</h5>
                  <span className=''>{card.mensaje}</span>
                </div>
              </div>
            )
          })
        ) : (
          [1, 2, 3, 4, 5, 6,7].map(task => {
            return (
              <Skeleton key={task} variant="rectangular" className='w-full my-3' height={80} />
            )
          })
        )
        }
      </main>
      <NavBar />
    </div>
  )
}
